const players = [
    // Flyweight
    { firstName: "Alexandre", lastName: "Pantoja", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2560746.png&w=350&h=254", age: 33, rank: 1 },
    { firstName: "Brandon", lastName: "Royval", weightClass: "Flyweight", photo: "https://a.espncdn.com/i/headshots/mma/players/full/4239928.png", age: 33, rank: 2 },
    { firstName: "Brandon", lastName: "Moreno", weightClass: "Flyweight", photo: "https://a.espncdn.com/i/headshots/mma/players/full/3027545.png", age: 30, rank: 3 },
    { firstName: "Amir", lastName: "Albazi", weightClass: "Flyweight", photo: "https://a.espncdn.com/i/headshots/mma/players/full/4684848.png", age: 26, rank: 4 },
    { firstName: "Kai", lastName: "Kara-France", weightClass: "Flyweight", photo: "https://a.espncdn.com/i/headshots/mma/players/full/4243885.png", age: 31, rank: 5 },
    { firstName: "Tatsuro", lastName: "Taira", weightClass: "Flyweight", photo: "https://ufc.com/images/2025-01/5/TAIRA_TATSURO_10-12.png", age: 28, rank: 6 },
    { firstName: "Manel", lastName: "Kape", weightClass: "Flyweight", photo: "https://ufc.com/images/2025-02/KAPE_MANEL_03-01.png", age: 30, rank: 7 },
    { firstName: "Alex", lastName: "Perez", weightClass: "Flyweight", photo: "https://ufc.com/images/2025-01/5/PEREZ_ALEX_06-15.png", age: 31, rank: 8 },
    { firstName: "Asu", lastName: "Almabayev", weightClass: "Flyweight", photo: "https://ufc.com/images/2025-02/ALMABAYEV_ASU_03-01.png", age: 29, rank: 9 },
    { firstName: "Steve", lastName: "Erceg", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4997217.png&w=350&h=254", age: 30, rank: 10 },
    { firstName: "Tagir", lastName: "Ulanbekov", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4294924.png&w=350&h=254", age: 29, rank: 11 },
    { firstName: "Tim", lastName: "Elliott", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2614020.png&w=350&h=254", age: 38, rank: 12 },
    { firstName: "Bruno", lastName: "Gustavo da Silva", weightClass: "Flyweight", photo: "https://a.espncdn.com/i/headshots/mma/players/full/3895544.png", age: 32, rank: 13 },
    { firstName: "Ramazan", lastName: "Temirov", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4895691.png&w=350&h=254", age: 31, rank: 14 },
    { firstName: "Joshua", lastName: "Van", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/5120301.png&w=350&h=254", age: 28, rank: 15 },
    { firstName: "Kai", lastName: "Asakura", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4336757.png&w=350&h=254", age: 28, rank: 16 },

    // Bantamweight
    { firstName: "Merab", lastName: "Dvalishvili", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3948572.png&w=350&h=254", age: 31, rank: 1 },
    { firstName: "Sean", lastName: "O'Malley", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4205093.png&w=350&h=254", age: 29, rank: 2 },
    { firstName: "Petr", lastName: "Yan", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4293517.png&w=350&h=254", age: 32, rank: 3 },
    { firstName: "Umar", lastName: "Nurmagomedov", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4569549.png&w=350&h=254", age: 28, rank: 4 },
    { firstName: "Cory", lastName: "Sandhagen", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4294504.png&w=350&h=254", age: 32, rank: 5 },
    { firstName: "Song", lastName: "Yadong", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3151289.png&w=350&h=254", age: 27, rank: 6 },
    { firstName: "Deiveson", lastName: "Figueiredo", weightClass: "Bantamweight", photo: "https://a.espncdn.com/i/headshots/mma/players/full/4189320.png", age: 35, rank: 7 },
    { firstName: "Marlon", lastName: "Vera", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3155424.png&w=350&h=254", age: 33, rank: 8 },
    { firstName: "Rob", lastName: "Font", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3090451.png&w=350&h=254", age: 35, rank: 9 },
    { firstName: "Henry", lastName: "Cejudo", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3023388.png&w=350&h=254", age: 37, rank: 10 },
    { firstName: "Mario", lastName: "Bautista", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4410868.png&w=350&h=254", age: 30, rank: 11 },
    { firstName: "Aiemann", lastName: "Zahabi", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4079149.png&w=350&h=254", age: 33, rank: 12 },
    { firstName: "Kyler", lastName: "Phillips", weightClass: "Bantamweight", photo: "https://ufc.com/images/2025-01/5/PHILLIPS_KYLER_10-19.png", age: 28, rank: 13 },
    { firstName: "Marcus", lastName: "McGhee", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4895760.png&w=350&h=254", age: 27, rank: 14 },
    { firstName: "Montel", lastName: "Jackson", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4339130.png&w=350&h=254", age: 32, rank: 15 },
    { firstName: "Vinicius", lastName: "Oliveira", weightClass: "Bantamweight", photo: "https://a.espncdn.com/i/headshots/mma/players/full/4884877.png", age: 29, rank: 16 },

    // Featherweight
    { firstName: "Alexander", lastName: "Volkanovski", weightClass: "Featherweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3949584.png&w=350&h=254", age: 36, rank: 1 },
    { firstName: "Max", lastName: "Holloway", weightClass: "Featherweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2614933.png&w=350&h=254", age: 33, rank: 2 },
    { firstName: "Diego", lastName: "Lopes", weightClass: "Featherweight", photo: "https://ufc.com/images/2025-04/LOPES_DIEGO_04-12.png", age: 30, rank: 3 },
    { firstName: "Ilia", lastName: "Topuria", weightClass: "Featherweight", photo: "https://a.espncdn.com/i/headshots/mma/players/full/4350812.png", age: 26, rank: 4 },
    { firstName: "Yair", lastName: "Rodríguez", weightClass: "Featherweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3155420.png&w=350&h=254", age: 30, rank: 5 },
    { firstName: "Movsar", lastName: "Evloev", weightClass: "Featherweight", photo: "https://a.espncdn.com/i/headshots/mma/players/full/4029275.png", age: 30, rank: 6 },
    { firstName: "Arnold", lastName: "Allen", weightClass: "Featherweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3902098.png&w=350&h=254", age: 29, rank: 7 },
    { firstName: "Brian", lastName: "Ortega", weightClass: "Featherweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3045737.png&w=350&h=254", age: 33, rank: 8 },
    { firstName: "Lerone", lastName: "Murphy", weightClass: "Featherweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4576101.png&w=350&h=254", age: 28, rank: 9 },
    { firstName: "Aljamain", lastName: "Sterling", weightClass: "Featherweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3031559.png&w=350&h=254", age: 33, rank: 10 },
    { firstName: "Josh", lastName: "Emmett", weightClass: "Featherweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4011299.png&w=350&h=254", age: 36, rank: 11 },
    { firstName: "Jean", lastName: "Silva", weightClass: "Featherweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/5145766.png&w=350&h=254", age: 31, rank: 12 },
    { firstName: "Youssef", lastName: "Zalal", weightClass: "Featherweight", photo: "https://ufc.com/images/2024-10/ZALAL_YOUSSEF_11-02.png", age: 28, rank: 13 },
    { firstName: "David", lastName: "Onama", weightClass: "Featherweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4897850.png&w=350&h=254", age: 25, rank: 14 },
    { firstName: "Dan", lastName: "Ige", weightClass: "Featherweight", photo: "https://a.espncdn.com/i/headshots/mma/players/full/4074001.png", age: 30, rank: 15 },
    { firstName: "Calvin", lastName: "Kattar", weightClass: "Featherweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3164030.png&w=350&h=254", age: 36, rank: 16 },

    // Lightweight
    { firstName: "Islam", lastName: "Makhachev", weightClass: "Lightweight", photo: "https://a.espncdn.com/i/headshots/mma/players/full/3332412.png", age: 33, rank: 1 },
    { firstName: "Arman", lastName: "Tsarukyan", weightClass: "Lightweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4419372.png&w=350&h=254", age: 26, rank: 2 },
    { firstName: "Charles", lastName: "Oliveira", weightClass: "Lightweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2504169.png&w=350&h=254", age: 38, rank: 3 },
    { firstName: "Justin", lastName: "Gaethje", weightClass: "Lightweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3022345.png&w=350&h=254", age: 35, rank: 4 },
    { firstName: "Dustin", lastName: "Poirier", weightClass: "Lightweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2506549.png&w=350&h=254", age: 36, rank: 5 },
    { firstName: "Dan", lastName: "Hooker", weightClass: "Lightweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3109135.png&w=350&h=254", age: 33, rank: 6 },
    { firstName: "Mateusz", lastName: "Gamrot", weightClass: "Lightweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3068125.png&w=350&h=254", age: 34, rank: 7 },
    { firstName: "Paddy", lastName: "Pimblett", weightClass: "Lightweight", photo: "https://a.espncdn.com/i/headshots/mma/players/full/4008549.png", age: 28, rank: 8 },
    { firstName: "Beneil", lastName: "Dariush", weightClass: "Lightweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3085551.png&w=350&h=254", age: 37, rank: 9 },
    { firstName: "Renato", lastName: "Moicano", weightClass: "Lightweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3028863.png&w=350&h=254", age: 37, rank: 10 },
    { firstName: "Rafael", lastName: "Fiziev", weightClass: "Lightweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4339488.png&w=350&h=254", age: 31, rank: 11 },
    { firstName: "Michael", lastName: "Chandler", weightClass: "Lightweight", photo: "https://a.espncdn.com/i/headshots/mma/players/full/2504988.png", age: 37, rank: 12 },
    { firstName: "Benoît", lastName: "Saint Denis", weightClass: "Lightweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4895362.png&w=350&h=254", age: 28, rank: 13 },
    { firstName: "Grant", lastName: "Dawson", weightClass: "Lightweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3931156.png&w=350&h=254", age: 29, rank: 14 },
    { firstName: "Joel", lastName: "Álvarez", weightClass: "Lightweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4411888.png&w=350&h=254", age: 30, rank: 15 },

    // Welterweight
    { firstName: "Jack", lastName: "Della Maddalena", weightClass: "Welterweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4828707.png&w=350&h=254", age: 27, rank: 1 },
    { firstName: "Belal", lastName: "Muhammad", weightClass: "Welterweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3172112.png&w=350&h=254", age: 35, rank: 2 },
    { firstName: "Sean", lastName: "Brady", weightClass: "Welterweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4295192.png&w=350&h=254", age: 32, rank: 3 },
    { firstName: "Shavkat", lastName: "Rakhmonov", weightClass: "Welterweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4020699.png&w=350&h=254", age: 31, rank: 4 },
    { firstName: "Leon", lastName: "Edwards", weightClass: "Welterweight", photo: "https://ufc.com/images/2025-03/EDWARDS_LEON_03-22.png", age: 32, rank: 5 },
    { firstName: "Kamaru", lastName: "Usman", weightClass: "Welterweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3088812.png&w=350&h=254", age: 36, rank: 6 },
    { firstName: "Ian", lastName: "Machado Garry", weightClass: "Welterweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4738092.png&w=350&h=254", age: 25, rank: 7 },
    { firstName: "Joaquin", lastName: "Buckley", weightClass: "Welterweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4024714.png&w=350&h=254", age: 30, rank: 8 },
    { firstName: "Gilbert", lastName: "Burns", weightClass: "Welterweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3090197.png&w=350&h=254", age: 37, rank: 9 },
    { firstName: "Colby", lastName: "Covington", weightClass: "Welterweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3088810.png&w=350&h=254", age: 36, rank: 10 },
    { firstName: "Geoff", lastName: "Neal", weightClass: "Welterweight", photo: "https://ufc.com/images/2025-01/5/NEAL_GEOFF_10-26.png", age: 35, rank: 11 },
    { firstName: "Stephen", lastName: "Thompson", weightClass: "Welterweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2615077.png&w=350&h=254", age: 40, rank: 12 },
    { firstName: "Michael", lastName: "Morales", weightClass: "Welterweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4869426.png&w=350&h=254", age: 25, rank: 13 },
    { firstName: "Carlos", lastName: "Prates", weightClass: "Welterweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4294832.png&w=350&h=254", age: 27, rank: 14 },
    { firstName: "Vicente", lastName: "Luque", weightClass: "Welterweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3045887.png&w=350&h=254", age: 31, rank: 15 },
    { firstName: "Michael", lastName: "Page", weightClass: "Welterweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3022067.png&w=350&h=254", age: 34, rank: 16 },

    // Middleweight
    { firstName: "Dricus", lastName: "Du Plessis", weightClass: "Middleweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3166126.png&w=350&h=254", age: 29, rank: 1 },
    { firstName: "Nassourdine", lastName: "Imavov", weightClass: "Middleweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4690539.png&w=350&h=254", age: 29, rank: 2 },
    { firstName: "Sean", lastName: "Strickland", weightClass: "Middleweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3093653.png&w=350&h=254", age: 32, rank: 3 },
    { firstName: "Khamzat", lastName: "Chimaev", weightClass: "Middleweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4684751.png&w=350&h=254", age: 31, rank: 4 },
    { firstName: "Israel", lastName: "Adesanya", weightClass: "Middleweight", photo: "https://ufc.com/images/2025-01/ADESANYA_ISRAEL_02-01.png", age: 35, rank: 5 },
    { firstName: "Robert", lastName: "Whittaker", weightClass: "Middleweight", photo: "https://ufc.com/images/2025-01/5/WHITTAKER_ROBERT_10-26.png", age: 33, rank: 6 },
    { firstName: "Caio", lastName: "Borralho", weightClass: "Middleweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4835137.png&w=350&h=254", age: 33, rank: 7 },
    { firstName: "Jared", lastName: "Cannonier", weightClass: "Middleweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3154860.png&w=350&h=254", age: 38, rank: 8 },
    { firstName: "Roman", lastName: "Dolidze", weightClass: "Middleweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4411508.png&w=350&h=254", age: 30, rank: 9 },
    { firstName: "Anthony", lastName: "Hernandez", weightClass: "Middleweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4290956.png&w=350&h=254", age: 30, rank: 10 },
    { firstName: "Marvin", lastName: "Vettori", weightClass: "Middleweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4001851.png&w=350&h=254", age: 33, rank: 11 },
    { firstName: "Brendan", lastName: "Allen", weightClass: "Middleweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4025699.png&w=350&h=254", age: 29, rank: 12 },
    { firstName: "Paulo", lastName: "Costa", weightClass: "Middleweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4080826.png&w=350&h=254", age: 32, rank: 13 },
    { firstName: "Reinier", lastName: "de Ridder", weightClass: "Middleweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4423880.png&w=350&h=254", age: 31, rank: 14 },
    { firstName: "Roman", lastName: "Kopylov", weightClass: "Middleweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4300149.png&w=350&h=254", age: 32, rank: 15 },
    { firstName: "Abusupiyan", lastName: "Magomedov", weightClass: "Middleweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3077822.png&w=350&h=254", age: 31, rank: 16 },

    // Light Heavyweight
    { firstName: "Magomed", lastName: "Ankalaev", weightClass: "Light Heavyweight", photo: "https://ufc.com/images/2025-03/ANKALAEV_MAGOMED_BELTMOCK.png", age: 32, rank: 1 },
    { firstName: "Alex", lastName: "Pereira", weightClass: "Light Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4705658.png&w=350&h=254", age: 36, rank: 2 },
    { firstName: "Jiří", lastName: "Procházka", weightClass: "Light Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3156612.png&w=350&h=254", age: 33, rank: 3 },
    { firstName: "Carlos", lastName: "Ulberg", weightClass: "Light Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4695736.png&w=350&h=254", age: 29, rank: 4 },
    { firstName: "Jamahal", lastName: "Hill", weightClass: "Light Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4425355.png&w=350&h=254", age: 33, rank: 5 },
    { firstName: "Jan", lastName: "Błachowicz", weightClass: "Light Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2506250.png&w=350&h=254", age: 41, rank: 6 },
    { firstName: "Aleksandar", lastName: "Rakić", weightClass: "Light Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4079314.png&w=350&h=254", age: 33, rank: 7 },
    { firstName: "Khalil", lastName: "Rountree", weightClass: "Light Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4028627.png&w=350&h=254", age: 33, rank: 8 },
    { firstName: "Dominick", lastName: "Reyes", weightClass: "Light Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4233039.png&w=350&h=254", age: 35, rank: 9 },
    { firstName: "Volkan", lastName: "Oezdemir", weightClass: "Light Heavyweight", photo: "https://ufc.com/images/2025-01/5/OEZDEMIR_VOLKAN_11-23.png", age: 34, rank: 10 },
    { firstName: "Nikita", lastName: "Krylov", weightClass: "Light Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3026263.png&w=350&h=254", age: 35, rank: 11 },
    { firstName: "Johnny", lastName: "Walker", weightClass: "Light Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3146944.png&w=350&h=254", age: 32, rank: 12 },
    { firstName: "Azamat", lastName: "Murzakanov", weightClass: "Light Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4227265.png&w=350&h=254", age: 28, rank: 13 },
    { firstName: "Zhang", lastName: "Mingyang", weightClass: "Light Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4845284.png&w=350&h=254", age: 30, rank: 14 },
    { firstName: "Bogdan", lastName: "Guskov", weightClass: "Light Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/5152109.png&w=350&h=254", age: 27, rank: 15 },
    { firstName: "Alonzo", lastName: "Menifield", weightClass: "Light Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3948876.png&w=350&h=254", age: 35, rank: 16 },

    // Heavyweight
    { firstName: "Jon", lastName: "Jones", weightClass: "Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2335639.png&w=350&h=254", age: 36, rank: 1 },
    { firstName: "Tom", lastName: "Aspinall", weightClass: "Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4010976.png&w=350&h=254", age: 30, rank: 2 },
    { firstName: "Ciryl", lastName: "Gane", weightClass: "Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4426000.png&w=350&h=254", age: 34, rank: 3 },
    { firstName: "Alexander", lastName: "Volkov", weightClass: "Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2993650.png&w=350&h=254", age: 35, rank: 4 },
    { firstName: "Sergei", lastName: "Pavlovich", weightClass: "Heavyweight", photo: "https://a.espncdn.com/i/headshots/mma/players/full/4217395.png", age: 30, rank: 5 },
    { firstName: "Curtis", lastName: "Blaydes", weightClass: "Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3922557.png&w=350&h=254", age: 35, rank: 6 },
    { firstName: "Jailton", lastName: "Almeida", weightClass: "Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4873640.png&w=350&h=254", age: 31, rank: 7 },
    { firstName: "Serghei", lastName: "Spivac", weightClass: "Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4421246.png&w=350&h=254", age: 30, rank: 8 },
    { firstName: "Marcin", lastName: "Tybura", weightClass: "Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3093559.png&w=350&h=254", age: 37, rank: 9 },
    { firstName: "Derrick", lastName: "Lewis", weightClass: "Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2560713.png&w=350&h=254", age: 37, rank: 10 },
    { firstName: "Tai", lastName: "Tuivasa", weightClass: "Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3722422.png&w=350&h=254", age: 33, rank: 11 },
    { firstName: "Waldo", lastName: "Cortes-Acosta", weightClass: "Heavyweight", photo: "https://ufc.com/images/2025-03/CORTES-ACOSTA_WALDO_03-15.png", age: 26, rank: 12 },
    { firstName: "Shamil", lastName: "Gaziev", weightClass: "Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/5145498.png&w=350&h=254", age: 28, rank: 13 },
    { firstName: "Mick", lastName: "Parkin", weightClass: "Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/5060505.png&w=350&h=254", age: 25, rank: 14 },
    { firstName: "Tallison", lastName: "Teixeira", weightClass: "Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/5212856.png&w=350&h=254", age: 32, rank: 15 },
    { firstName: "Martin", lastName: "Buday", weightClass: "Heavyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4406574.png&w=350&h=254", age: 24, rank: 16 },

    // Strawweight
    { firstName: "Zhang", lastName: "Weili", weightClass: "Strawweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4350762.png&w=350&h=254", age: 34, rank: 1 },
    { firstName: "Virna", lastName: "Jandiroba", weightClass: "Strawweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4289516.png&w=350&h=254", age: 34, rank: 2 },
    { firstName: "Tatiana", lastName: "Suarez", weightClass: "Strawweight", photo: "https://a.espncdn.com/i/headshots/mma/players/full/4020435.png", age: 36, rank: 3 },
    { firstName: "Yan", lastName: "Xiaonan", weightClass: "Strawweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4275487.png&w=350&h=254", age: 33, rank: 4 },
    { firstName: "Amanda", lastName: "Lemos", weightClass: "Strawweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4233196.png&w=350&h=254", age: 33, rank: 5 },
    { firstName: "Jéssica", lastName: "Andrade", weightClass: "Strawweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3024395.png&w=350&h=254", age: 36, rank: 6 },
    { firstName: "Mackenzie", lastName: "Dern", weightClass: "Strawweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4021217.png&w=350&h=254", age: 35, rank: 7 },
    { firstName: "Amanda", lastName: "Ribas", weightClass: "Strawweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4221863.png&w=350&h=254", age: 34, rank: 8 },
    { firstName: "Iasmin", lastName: "Lucindo", weightClass: "Strawweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/5080935.png&w=350&h=254", age: 30, rank: 9 },
    { firstName: "Gillian", lastName: "Robertson", weightClass: "Strawweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4089026.png&w=350&h=254", age: 31, rank: 10 },
    { firstName: "Tabatha", lastName: "Ricci", weightClass: "Strawweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4868095.png&w=350&h=254", age: 28, rank: 11 },
    { firstName: "Angela", lastName: "Hill", weightClass: "Strawweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3115931.png&w=350&h=254", age: 38, rank: 12 },
    { firstName: "Tecia", lastName: "Pennington", weightClass: "Strawweight", photo: "https://a.espncdn.com/i/headshots/mma/players/full/3032972.png", age: 31, rank: 13 },
    { firstName: "Luana", lastName: "Pinheiro", weightClass: "Strawweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4689229.png&w=350&h=254", age: 28, rank: 14 },
    { firstName: "Loma", lastName: "Lookboonmee", weightClass: "Strawweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4292347.png&w=350&h=254", age: 32, rank: 15 },

    // Women's Flyweight
    { firstName: "Valentina", lastName: "Shevchenko", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2554705.png&w=350&h=254", age: 36, rank: 1 },
    { firstName: "Natália", lastName: "Silva", weightClass: "Flyweight", photo: "https://a.espncdn.com/i/headshots/mma/players/full/4054605.png", age: 25, rank: 2 },
    { firstName: "Manon", lastName: "Fiorot", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4608674.png&w=350&h=254", age: 31, rank: 3 },
    { firstName: "Alexa", lastName: "Grasso", weightClass: "Flyweight", photo: "https://a.espncdn.com/i/headshots/mma/players/full/3136287.png", age: 32, rank: 4 },
    { firstName: "Erin", lastName: "Blanchfield", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4350796.png&w=350&h=254", age: 24, rank: 5 },
    { firstName: "Maycee", lastName: "Barber", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4246307.png&w=350&h=254", age: 25, rank: 6 },
    { firstName: "Jasmine", lastName: "Jasudavicius", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4835135.png&w=350&h=254", age: 29, rank: 7 },
    { firstName: "Rose", lastName: "Namajunas", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3032973.png&w=350&h=254", age: 33, rank: 8 },
    { firstName: "Viviane", lastName: "Araújo", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4379362.png&w=350&h=254", age: 36, rank: 9 },
    { firstName: "Jessica", lastName: "Andrade", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3024395.png&w=350&h=254", age: 36, rank: 10 },
    { firstName: "Tracy", lastName: "Cortez", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4243624.png&w=350&h=254", age: 29, rank: 11 },
    { firstName: "Karine", lastName: "Silva", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3309918.png&w=350&h=254", age: 31, rank: 12 },
    { firstName: "Miranda", lastName: "Maverick", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4065598.png&w=350&h=254", age: 27, rank: 13 },
    { firstName: "Casey", lastName: "O'Neill", weightClass: "Flyweight", photo: "https://a.espncdn.com/i/headshots/mma/players/full/4699589.png", age: 25, rank: 14 },
    { firstName: "Ariane", lastName: "da Silva", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4227318.png&w=350&h=254", age: 28, rank: 15 },
    { firstName: "JJ", lastName: "Aldrich", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3136289.png&w=350&h=254", age: 36, rank: 16 },

    // Women's Bantamweight
    { firstName: "Julianna", lastName: "Peña", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2951361.png&w=350&h=254", age: 35, rank: 1 },
    { firstName: "Raquel", lastName: "Pennington", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2995167.png&w=350&h=254", age: 38, rank: 2 },
    { firstName: "Kayla", lastName: "Harrison", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4332765.png&w=350&h=254", age: 35, rank: 3 },
    { firstName: "Ketlen", lastName: "Vieira", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4039865.png&w=350&h=254", age: 34, rank: 4 },
    { firstName: "Norma", lastName: "Dumont", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4418784.png&w=350&h=254", age: 34, rank: 5 },
    { firstName: "Macy", lastName: "Chiasson", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4334306.png&w=350&h=254", age: 30, rank: 6 },
    { firstName: "Irene", lastName: "Aldana", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3136286.png&w=350&h=254", age: 35, rank: 7 },
    { firstName: "Ailín", lastName: "Pérez", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/5075333.png&w=350&h=254", age: 27, rank: 8 },
    { firstName: "Mayra", lastName: "Bueno Silva", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4371001.png&w=350&h=254", age: 29, rank: 9 },
    { firstName: "Yana", lastName: "Santos", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/3154898.png&w=350&h=254", age: 36, rank: 10 },
    { firstName: "Karol", lastName: "Rosa", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4292349.png&w=350&h=254", age: 33, rank: 11 },
    { firstName: "Jacqueline", lastName: "Cavalcanti", weightClass: "Bantamweight", photo: "https://a.espncdn.com/i/headshots/mma/players/full/4916251.png", age: 29, rank: 12 },
    { firstName: "Nora", lastName: "Cornolle", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4916974.png&w=350&h=254", age: 29, rank: 13 },
    { firstName: "Miesha", lastName: "Tate", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2553021.png&w=350&h=254", age: 41, rank: 14 },
    { firstName: "Joselyne", lastName: "Edwards", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4397782.png&w=350&h=254", age: 31, rank: 15 },
    { firstName: "Chelsea", lastName: "Chandler", weightClass: "Bantamweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4319785.png&w=350&h=254", age: 30, rank: 16 },
];
