const placeholderPhoto = "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2335639.png&w=350&h=254";

const players = [
    // Flyweight
    { firstName: "Alexandre", lastName: "Pantoja", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2560746.png&w=350&h=254", age: 33 },
    { firstName: "Brandon", lastName: "Royval", weightClass: "Flyweight", photo: "https://a.espncdn.com/i/headshots/mma/players/full/4239928.png", age: 33 },
    { firstName: "Brandon", lastName: "Moreno", weightClass: "Flyweight", photo: "https://a.espncdn.com/i/headshots/mma/players/full/3027545.png", age: 30 },
    { firstName: "Amir", lastName: "Albazi", weightClass: "Flyweight", photo: "https://a.espncdn.com/i/headshots/mma/players/full/4684848.png", age: 26 },
    { firstName: "Kai", lastName: "Kara-France", weightClass: "Flyweight", photo: "https://a.espncdn.com/i/headshots/mma/players/full/4243885.png", age: 31 },
    { firstName: "Tatsuro", lastName: "Taira", weightClass: "Flyweight", photo: "https://ufc.com/images/2025-01/5/TAIRA_TATSURO_10-12.png", age: 28 },
    { firstName: "Manel", lastName: "Kape", weightClass: "Flyweight", photo: "https://ufc.com/images/2025-02/KAPE_MANEL_03-01.png", age: 30 },
    { firstName: "Alex", lastName: "Perez", weightClass: "Flyweight", photo: "https://ufc.com/images/2025-01/5/PEREZ_ALEX_06-15.png", age: 31 },
    { firstName: "Asu", lastName: "Almabayev", weightClass: "Flyweight", photo: "https://ufc.com/images/2025-02/ALMABAYEV_ASU_03-01.png", age: 29 },
    { firstName: "Steve", lastName: "Erceg", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4997217.png&w=350&h=254", age: 30 },
    { firstName: "Tagir", lastName: "Ulanbekov", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4294924.png&w=350&h=254", age: 29 },
    { firstName: "Tim", lastName: "Elliott", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/2614020.png&w=350&h=254", age: 38 },
    { firstName: "Bruno", lastName: "Gustavo da Silva", weightClass: "Flyweight", photo: "https://a.espncdn.com/i/headshots/mma/players/full/3895544.png", age: 32 },
    { firstName: "Ramazan", lastName: "Temirov", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4895691.png&w=350&h=254", age: 31 },
    { firstName: "Joshua", lastName: "Van", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/5120301.png&w=350&h=254", age: 28 },
    { firstName: "Kai", lastName: "Asakura", weightClass: "Flyweight", photo: "https://a.espncdn.com/combiner/i?img=/i/headshots/mma/players/full/4336757.png&w=350&h=254", age: 28 },
    // Bantamweight
    { firstName: "Merab", lastName: "Dvalishvili", weightClass: "Bantamweight", photo: placeholderPhoto, age: 31 },
    { firstName: "Sean", lastName: "O'Malley", weightClass: "Bantamweight", photo: placeholderPhoto, age: 29 },
    { firstName: "Petr", lastName: "Yan", weightClass: "Bantamweight", photo: placeholderPhoto, age: 32 },
    { firstName: "Umar", lastName: "Nurmagomedov", weightClass: "Bantamweight", photo: placeholderPhoto, age: 28 },
    { firstName: "Cory", lastName: "Sandhagen", weightClass: "Bantamweight", photo: placeholderPhoto, age: 32 },
    { firstName: "Song", lastName: "Yadong", weightClass: "Bantamweight", photo: placeholderPhoto, age: 27 },
    { firstName: "Deiveson", lastName: "Figueiredo", weightClass: "Bantamweight", photo: placeholderPhoto, age: 35 },
    { firstName: "Marlon", lastName: "Vera", weightClass: "Bantamweight", photo: placeholderPhoto, age: 33 },
    { firstName: "Rob", lastName: "Font", weightClass: "Bantamweight", photo: placeholderPhoto, age: 35 },
    { firstName: "Henry", lastName: "Cejudo", weightClass: "Bantamweight", photo: placeholderPhoto, age: 37 },
    { firstName: "Mario", lastName: "Bautista", weightClass: "Bantamweight", photo: placeholderPhoto, age: 30 },
    { firstName: "Aiemann", lastName: "Zahabi", weightClass: "Bantamweight", photo: placeholderPhoto, age: 33 },
    { firstName: "Kyler", lastName: "Phillips", weightClass: "Bantamweight", photo: placeholderPhoto, age: 28 },
    { firstName: "Marcus", lastName: "McGhee", weightClass: "Bantamweight", photo: placeholderPhoto, age: 27 },
    { firstName: "Montel", lastName: "Jackson", weightClass: "Bantamweight", photo: placeholderPhoto, age: 32 },
    { firstName: "Vinicius", lastName: "Oliveira", weightClass: "Bantamweight", photo: placeholderPhoto, age: 29 },
    // Featherweight
    { firstName: "Alexander", lastName: "Volkanovski", weightClass: "Featherweight", photo: placeholderPhoto, age: 36 },
    { firstName: "Max", lastName: "Holloway", weightClass: "Featherweight", photo: placeholderPhoto, age: 33 },
    { firstName: "Diego", lastName: "Lopes", weightClass: "Featherweight", photo: placeholderPhoto, age: 30 },
    { firstName: "Ilia", lastName: "Topuria", weightClass: "Featherweight", photo: placeholderPhoto, age: 26 },
    { firstName: "Yair", lastName: "Rodríguez", weightClass: "Featherweight", photo: placeholderPhoto, age: 30 },
    { firstName: "Movsar", lastName: "Evloev", weightClass: "Featherweight", photo: placeholderPhoto, age: 30 },
    { firstName: "Arnold", lastName: "Allen", weightClass: "Featherweight", photo: placeholderPhoto, age: 29 },
    { firstName: "Brian", lastName: "Ortega", weightClass: "Featherweight", photo: placeholderPhoto, age: 33 },
    { firstName: "Lerone", lastName: "Murphy", weightClass: "Featherweight", photo: placeholderPhoto, age: 28 },
    { firstName: "Aljamain", lastName: "Sterling", weightClass: "Featherweight", photo: placeholderPhoto, age: 33 },
    { firstName: "Josh", lastName: "Emmett", weightClass: "Featherweight", photo: placeholderPhoto, age: 36 },
    { firstName: "Jean", lastName: "Silva", weightClass: "Featherweight", photo: placeholderPhoto, age: 31 },
    { firstName: "Youssef", lastName: "Zalal", weightClass: "Featherweight", photo: placeholderPhoto, age: 28 },
    { firstName: "David", lastName: "Onama", weightClass: "Featherweight", photo: placeholderPhoto, age: 25 },
    { firstName: "Dan", lastName: "Ige", weightClass: "Featherweight", photo: placeholderPhoto, age: 30 },
    { firstName: "Calvin", lastName: "Kattar", weightClass: "Featherweight", photo: placeholderPhoto, age: 36 },
    // Lightweight
    { firstName: "Islam", lastName: "Makhachev", weightClass: "Lightweight", photo: placeholderPhoto, age: 33 },
    { firstName: "Arman", lastName: "Tsarukyan", weightClass: "Lightweight", photo: placeholderPhoto, age: 26 },
    { firstName: "Charles", lastName: "Oliveira", weightClass: "Lightweight", photo: placeholderPhoto, age: 38 },
    { firstName: "Justin", lastName: "Gaethje", weightClass: "Lightweight", photo: placeholderPhoto, age: 35 },
    { firstName: "Dustin", lastName: "Poirier", weightClass: "Lightweight", photo: placeholderPhoto, age: 36 },
    { firstName: "Dan", lastName: "Hooker", weightClass: "Lightweight", photo: placeholderPhoto, age: 33 },
    { firstName: "Mateusz", lastName: "Gamrot", weightClass: "Lightweight", photo: placeholderPhoto, age: 34 },
    { firstName: "Paddy", lastName: "Pimblett", weightClass: "Lightweight", photo: placeholderPhoto, age: 28 },
    { firstName: "Beneil", lastName: "Dariush", weightClass: "Lightweight", photo: placeholderPhoto, age: 37 },
    { firstName: "Renato", lastName: "Moicano", weightClass: "Lightweight", photo: placeholderPhoto, age: 37 },
    { firstName: "Rafael", lastName: "Fiziev", weightClass: "Lightweight", photo: placeholderPhoto, age: 31 },
    { firstName: "Michael", lastName: "Chandler", weightClass: "Lightweight", photo: placeholderPhoto, age: 37 },
    { firstName: "Benoît", lastName: "Saint Denis", weightClass: "Lightweight", photo: placeholderPhoto, age: 28 },
    { firstName: "Grant", lastName: "Dawson", weightClass: "Lightweight", photo: placeholderPhoto, age: 29 },
    { firstName: "Joel", lastName: "Álvarez", weightClass: "Lightweight", photo: placeholderPhoto, age: 30 },
    // Welterweight
    { firstName: "Jack", lastName: "Della Maddalena", weightClass: "Welterweight", photo: placeholderPhoto, age: 27 },
    { firstName: "Belal", lastName: "Muhammad", weightClass: "Welterweight", photo: placeholderPhoto, age: 35 },
    { firstName: "Sean", lastName: "Brady", weightClass: "Welterweight", photo: placeholderPhoto, age: 32 },
    { firstName: "Shavkat", lastName: "Rakhmonov", weightClass: "Welterweight", photo: placeholderPhoto, age: 31 },
    { firstName: "Leon", lastName: "Edwards", weightClass: "Welterweight", photo: placeholderPhoto, age: 32 },
    { firstName: "Kamaru", lastName: "Usman", weightClass: "Welterweight", photo: placeholderPhoto, age: 36 },
    { firstName: "Ian", lastName: "Machado Garry", weightClass: "Welterweight", photo: placeholderPhoto, age: 25 },
    { firstName: "Joaquin", lastName: "Buckley", weightClass: "Welterweight", photo: placeholderPhoto, age: 30 },
    { firstName: "Gilbert", lastName: "Burns", weightClass: "Welterweight", photo: placeholderPhoto, age: 37 },
    { firstName: "Colby", lastName: "Covington", weightClass: "Welterweight", photo: placeholderPhoto, age: 36 },
    { firstName: "Geoff", lastName: "Neal", weightClass: "Welterweight", photo: placeholderPhoto, age: 35 },
    { firstName: "Stephen", lastName: "Thompson", weightClass: "Welterweight", photo: placeholderPhoto, age: 40 },
    { firstName: "Michael", lastName: "Morales", weightClass: "Welterweight", photo: placeholderPhoto, age: 25 },
    { firstName: "Carlos", lastName: "Prates", weightClass: "Welterweight", photo: placeholderPhoto, age: 27 },
    { firstName: "Vicente", lastName: "Luque", weightClass: "Welterweight", photo: placeholderPhoto, age: 31 },
    { firstName: "Michael", lastName: "Page", weightClass: "Welterweight", photo: placeholderPhoto, age: 34 },
    { firstName: "Kevin", lastName: "Holland", weightClass: "Welterweight", photo: placeholderPhoto, age: 31 },
    // Middleweight
    { firstName: "Dricus", lastName: "Du Plessis", weightClass: "Middleweight", photo: placeholderPhoto, age: 29 },
    { firstName: "Nassourdine", lastName: "Imavov", weightClass: "Middleweight", photo: placeholderPhoto, age: 29 },
    { firstName: "Sean", lastName: "Strickland", weightClass: "Middleweight", photo: placeholderPhoto, age: 32 },
    { firstName: "Khamzat", lastName: "Chimaev", weightClass: "Middleweight", photo: placeholderPhoto, age: 31 },
    { firstName: "Israel", lastName: "Adesanya", weightClass: "Middleweight", photo: placeholderPhoto, age: 35 },
    { firstName: "Robert", lastName: "Whittaker", weightClass: "Middleweight", photo: placeholderPhoto, age: 33 },
    { firstName: "Caio", lastName: "Borralho", weightClass: "Middleweight", photo: placeholderPhoto, age: 33 },
    { firstName: "Jared", lastName: "Cannonier", weightClass: "Middleweight", photo: placeholderPhoto, age: 38 },
    { firstName: "Roman", lastName: "Dolidze", weightClass: "Middleweight", photo: placeholderPhoto, age: 30 },
    { firstName: "Anthony", lastName: "Hernandez", weightClass: "Middleweight", photo: placeholderPhoto, age: 30 },
    { firstName: "Marvin", lastName: "Vettori", weightClass: "Middleweight", photo: placeholderPhoto, age: 33 },
    { firstName: "Brendan", lastName: "Allen", weightClass: "Middleweight", photo: placeholderPhoto, age: 29 },
    { firstName: "Paulo", lastName: "Costa", weightClass: "Middleweight", photo: placeholderPhoto, age: 32 },
    { firstName: "Reinier", lastName: "de Ridder", weightClass: "Middleweight", photo: placeholderPhoto, age: 31 },
    { firstName: "Roman", lastName: "Kopylov", weightClass: "Middleweight", photo: placeholderPhoto, age: 32 },
    { firstName: "Abusupiyan", lastName: "Magomedov", weightClass: "Middleweight", photo: placeholderPhoto, age: 31 },
    // Light Heavyweight
    { firstName: "Magomed", lastName: "Ankalaev", weightClass: "Light Heavyweight", photo: placeholderPhoto, age: 32 },
    { firstName: "Alex", lastName: "Pereira", weightClass: "Light Heavyweight", photo: placeholderPhoto, age: 36 },
    { firstName: "Jiří", lastName: "Procházka", weightClass: "Light Heavyweight", photo: placeholderPhoto, age: 33 },
    { firstName: "Carlos", lastName: "Ulberg", weightClass: "Light Heavyweight", photo: placeholderPhoto, age: 29 },
    { firstName: "Jamahal", lastName: "Hill", weightClass: "Light Heavyweight", photo: placeholderPhoto, age: 33 },
    { firstName: "Jan", lastName: "Błachowicz", weightClass: "Light Heavyweight", photo: placeholderPhoto, age: 41 },
    { firstName: "Aleksandar", lastName: "Rakić", weightClass: "Light Heavyweight", photo: placeholderPhoto, age: 33 },
    { firstName: "Khalil", lastName: "Rountree", weightClass: "Light Heavyweight", photo: placeholderPhoto, age: 33 },
    { firstName: "Dominick", lastName: "Reyes", weightClass: "Light Heavyweight", photo: placeholderPhoto, age: 35 },
    { firstName: "Volkan", lastName: "Oezdemir", weightClass: "Light Heavyweight", photo: placeholderPhoto, age: 34 },
    { firstName: "Nikita", lastName: "Krylov", weightClass: "Light Heavyweight", photo: placeholderPhoto, age: 35 },
    { firstName: "Johnny", lastName: "Walker", weightClass: "Light Heavyweight", photo: placeholderPhoto, age: 32 },
    { firstName: "Azamat", lastName: "Murzakanov", weightClass: "Light Heavyweight", photo: placeholderPhoto, age: 28 },
    { firstName: "Zhang", lastName: "Mingyang", weightClass: "Light Heavyweight", photo: placeholderPhoto, age: 30 },
    { firstName: "Bogdan", lastName: "Guskov", weightClass: "Light Heavyweight", photo: placeholderPhoto, age: 27 },
    { firstName: "Alonzo", lastName: "Menifield", weightClass: "Light Heavyweight", photo: placeholderPhoto, age: 35 },
    // Heavyweight
    { firstName: "Jon", lastName: "Jones", weightClass: "Heavyweight", photo: placeholderPhoto, age: 36 },
    { firstName: "Tom", lastName: "Aspinall", weightClass: "Heavyweight", photo: placeholderPhoto, age: 30 },
    { firstName: "Ciryl", lastName: "Gane", weightClass: "Heavyweight", photo: placeholderPhoto, age: 34 },
    { firstName: "Alexander", lastName: "Volkov", weightClass: "Heavyweight", photo: placeholderPhoto, age: 35 },
    { firstName: "Sergei", lastName: "Pavlovich", weightClass: "Heavyweight", photo: placeholderPhoto, age: 30 },
    { firstName: "Curtis", lastName: "Blaydes", weightClass: "Heavyweight", photo: placeholderPhoto, age: 35 },
    { firstName: "Jailton", lastName: "Almeida", weightClass: "Heavyweight", photo: placeholderPhoto, age: 31 },
    { firstName: "Serghei", lastName: "Spivac", weightClass: "Heavyweight", photo: placeholderPhoto, age: 30 },
    { firstName: "Marcin", lastName: "Tybura", weightClass: "Heavyweight", photo: placeholderPhoto, age: 37 },
    { firstName: "Derrick", lastName: "Lewis", weightClass: "Heavyweight", photo: placeholderPhoto, age: 37 },
    { firstName: "Tai", lastName: "Tuivasa", weightClass: "Heavyweight", photo: placeholderPhoto, age: 33 },
    { firstName: "Waldo", lastName: "Cortes-Acosta", weightClass: "Heavyweight", photo: placeholderPhoto, age: 26 },
    { firstName: "Shamil", lastName: "Gaziev", weightClass: "Heavyweight", photo: placeholderPhoto, age: 28 },
    { firstName: "Mick", lastName: "Parkin", weightClass: "Heavyweight", photo: placeholderPhoto, age: 25 },
    { firstName: "Tallison", lastName: "Teixeira", weightClass: "Heavyweight", photo: placeholderPhoto, age: 32 },
    { firstName: "Martin", lastName: "Buday", weightClass: "Heavyweight", photo: placeholderPhoto, age: 24 },
    // Strawweight
    { firstName: "Zhang", lastName: "Weili", weightClass: "Strawweight", photo: placeholderPhoto, age: 34 },
    { firstName: "Virna", lastName: "Jandiroba", weightClass: "Strawweight", photo: placeholderPhoto, age: 34 },
    { firstName: "Tatiana", lastName: "Suarez", weightClass: "Strawweight", photo: placeholderPhoto, age: 36 },
    { firstName: "Yan", lastName: "Xiaonan", weightClass: "Strawweight", photo: placeholderPhoto, age: 33 },
    { firstName: "Amanda", lastName: "Lemos", weightClass: "Strawweight", photo: placeholderPhoto, age: 33 },
    { firstName: "Jéssica", lastName: "Andrade", weightClass: "Strawweight", photo: placeholderPhoto, age: 36 },
    { firstName: "Mackenzie", lastName: "Dern", weightClass: "Strawweight", photo: placeholderPhoto, age: 35 },
    { firstName: "Amanda", lastName: "Ribas", weightClass: "Strawweight", photo: placeholderPhoto, age: 34 },
    { firstName: "Iasmin", lastName: "Lucindo", weightClass: "Strawweight", photo: placeholderPhoto, age: 30 },
    { firstName: "Gillian", lastName: "Robertson", weightClass: "Strawweight", photo: placeholderPhoto, age: 31 },
    { firstName: "Tabatha", lastName: "Ricci", weightClass: "Strawweight", photo: placeholderPhoto, age: 28 },
    { firstName: "Angela", lastName: "Hill", weightClass: "Strawweight", photo: placeholderPhoto, age: 38 },
    { firstName: "Tecia", lastName: "Pennington", weightClass: "Strawweight", photo: placeholderPhoto, age: 31 },
    { firstName: "Luana", lastName: "Pinheiro", weightClass: "Strawweight", photo: placeholderPhoto, age: 28 },
    { firstName: "Loma", lastName: "Lookboonmee", weightClass: "Strawweight", photo: placeholderPhoto, age: 32 },
    // Women's Flyweight
    { firstName: "Valentina", lastName: "Shevchenko", weightClass: "Flyweight", photo: placeholderPhoto, age: 36 },
    { firstName: "Natália", lastName: "Silva", weightClass: "Flyweight", photo: placeholderPhoto, age: 25 },
    { firstName: "Manon", lastName: "Fiorot", weightClass: "Flyweight", photo: placeholderPhoto, age: 31 },
    { firstName: "Alexa", lastName: "Grasso", weightClass: "Flyweight", photo: placeholderPhoto, age: 32 },
    { firstName: "Erin", lastName: "Blanchfield", weightClass: "Flyweight", photo: placeholderPhoto, age: 24 },
    { firstName: "Maycee", lastName: "Barber", weightClass: "Flyweight", photo: placeholderPhoto, age: 25 },
    { firstName: "Jasmine", lastName: "Jasudavicius", weightClass: "Flyweight", photo: placeholderPhoto, age: 29 },
    { firstName: "Rose", lastName: "Namajunas", weightClass: "Flyweight", photo: placeholderPhoto, age: 33 },
    { firstName: "Viviane", lastName: "Araújo", weightClass: "Flyweight", photo: placeholderPhoto, age: 36 },
    { firstName: "Jessica", lastName: "Andrade", weightClass: "Flyweight", photo: placeholderPhoto, age: 36 },
    { firstName: "Tracy", lastName: "Cortez", weightClass: "Flyweight", photo: placeholderPhoto, age: 29 },
    { firstName: "Karine", lastName: "Silva", weightClass: "Flyweight", photo: placeholderPhoto, age: 31 },
    { firstName: "Miranda", lastName: "Maverick", weightClass: "Flyweight", photo: placeholderPhoto, age: 27 },
    { firstName: "Casey", lastName: "O'Neill", weightClass: "Flyweight", photo: placeholderPhoto, age: 25 },
    { firstName: "Ariane", lastName: "da Silva", weightClass: "Flyweight", photo: placeholderPhoto, age: 28 },
    { firstName: "JJ", lastName: "Aldrich", weightClass: "Flyweight", photo: placeholderPhoto, age: 36 },
    // Women's Bantamweight
    { firstName: "Julianna", lastName: "Peña", weightClass: "Bantamweight", photo: placeholderPhoto, age: 35 },
    { firstName: "Raquel", lastName: "Pennington", weightClass: "Bantamweight", photo: placeholderPhoto, age: 38 },
    { firstName: "Kayla", lastName: "Harrison", weightClass: "Bantamweight", photo: placeholderPhoto, age: 35 },
    { firstName: "Ketlen", lastName: "Vieira", weightClass: "Bantamweight", photo: placeholderPhoto, age: 34 },
    { firstName: "Norma", lastName: "Dumont", weightClass: "Bantamweight", photo: placeholderPhoto, age: 34 },
    { firstName: "Macy", lastName: "Chiasson", weightClass: "Bantamweight", photo: placeholderPhoto, age: 30 },
    { firstName: "Irene", lastName: "Aldana", weightClass: "Bantamweight", photo: placeholderPhoto, age: 35 },
    { firstName: "Ailín", lastName: "Pérez", weightClass: "Bantamweight", photo: placeholderPhoto, age: 27 },
    { firstName: "Mayra", lastName: "Bueno Silva", weightClass: "Bantamweight", photo: placeholderPhoto, age: 29 },
    { firstName: "Yana", lastName: "Santos", weightClass: "Bantamweight", photo: placeholderPhoto, age: 36 },
    { firstName: "Karol", lastName: "Rosa", weightClass: "Bantamweight", photo: placeholderPhoto, age: 33 },
    { firstName: "Jacqueline", lastName: "Cavalcanti", weightClass: "Bantamweight", photo: placeholderPhoto, age: 29 },
    { firstName: "Nora", lastName: "Cornolle", weightClass: "Bantamweight", photo: placeholderPhoto, age: 29 },
    { firstName: "Miesha", lastName: "Tate", weightClass: "Bantamweight", photo: placeholderPhoto, age: 41 },
    { firstName: "Joselyne", lastName: "Edwards", weightClass: "Bantamweight", photo: placeholderPhoto, age: 31 },
    { firstName: "Chelsea", lastName: "Chandler", weightClass: "Bantamweight", photo: placeholderPhoto, age: 30 },
    // Women's Featherweight
    { firstName: "Amanda", lastName: "Nunes", weightClass: "Featherweight", photo: placeholderPhoto, age: 36 },
    { firstName: "Macy", lastName: "Chiasson", weightClass: "Featherweight", photo: placeholderPhoto, age: 30 },
    { firstName: "Norma", lastName: "Dumont", weightClass: "Featherweight", photo: placeholderPhoto, age: 34 },
    { firstName: "Chelsea", lastName: "Chandler", weightClass: "Featherweight", photo: placeholderPhoto, age: 30 },
    { firstName: "Joseane", lastName: "Nunes", weightClass: "Featherweight", photo: placeholderPhoto, age: 36 },
    { firstName: "Stephanie", lastName: "Egger", weightClass: "Featherweight", photo: placeholderPhoto, age: 33 },
    { firstName: "Joselyne", lastName: "Edwards", weightClass: "Featherweight", photo: placeholderPhoto, age: 31 },
    { firstName: "Leah", lastName: "Letson", weightClass: "Featherweight", photo: placeholderPhoto, age: 33 }
];
